"""add delivered_at to trip_stops

Revision ID: b4eb596814b7
Revises: fcb277da8101
Create Date: 2026-07-13 22:36:33.052103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b4eb596814b7'
down_revision: Union[str, None] = 'fcb277da8101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_stops', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_stops', 'delivered_at')
    # ### end Alembic commands ###
