"""Flota real de la empresa, importada de "FLOTA UP - 2026" (hoja oficial
de flota por operacion, julio 2026).

Reglas de este archivo:
- Fichas reales; NUNCA incluir placas, chasis ni VIN (peticion explicita).
- "operation" refleja la operacion a la que esta asignada la unidad.
- Compartimientos con product_code=None son flexibles: admiten cualquier
  producto blanco (diesel/gasolina regular y premium) y la eleccion puede
  variar por viaje. Aplica a todas las operaciones WOP.
- JET PUNTA CANA / JET TERPEL: compartimientos dedicados a JET_A1.
- FUEL OIL: dedicados a FUEL_OIL, excepto L-61 cuyo tanque es WOP.
- Quedaron FUERA por no tener desglose de compartimientos valido en la
  hoja (pendientes de datos): L-16, L-64, L-65, L-66, L-67; ademas las
  operaciones GLP (sin desglose), cabezotes sin tanque, unidades vendidas
  y las secciones sin identificar.
"""

FLEET: list[dict] = [
    {
        "code": 'L-119',
        "operation": 'TRANSPORTE LIZANDRO',
        "chassis_brand": 'FREIGHTLINER',
        "chassis_year": 2019,
        "tank_brand": 'HEIL',
        "tank_year": 2003,
        "total_capacity": 12000,
        "compartments": [
            {"capacity": 4000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 1000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 3000, "product_code": None},
        ],
        "status": 'active',
        "notes": 'Propiedad: TL',
    },
    {
        "code": 'L-54',
        "operation": 'TRANSPORTE LIZANDRO',
        "chassis_brand": 'FREIGHTLINER',
        "chassis_year": 2017,
        "tank_brand": 'HEIL',
        "tank_year": 2025,
        "total_capacity": 10000,
        "compartments": [
            {"capacity": 3000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 1000, "product_code": None},
        ],
        "status": 'active',
        "notes": 'Propiedad: TL',
    },
    {
        "code": 'L-53',
        "operation": 'TRANSPORTE LIZANDRO',
        "chassis_brand": 'FREIGHTLINER',
        "chassis_year": 2017,
        "tank_brand": 'HEIL',
        "tank_year": 2025,
        "total_capacity": 10000,
        "compartments": [
            {"capacity": 3000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 1000, "product_code": None},
        ],
        "status": 'active',
        "notes": 'Propiedad: TL',
    },
    {
        "code": 'L-50',
        "operation": 'TRANSPORTE LIZANDRO',
        "chassis_brand": 'SCANIA',
        "chassis_year": 2017,
        "tank_brand": 'BEALL',
        "tank_year": 2018,
        "total_capacity": 12000,
        "compartments": [
            {"capacity": 4000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 1000, "product_code": None},
            {"capacity": 3000, "product_code": None},
        ],
        "status": 'active',
        "notes": 'Propiedad: UP debe pasar a TL',
    },
    {
        "code": 'F-04',
        "operation": 'TRANSPORTE LIZANDRO',
        "chassis_brand": 'FREIGHTLINER',
        "chassis_year": 2020,
        "tank_brand": 'HEIL',
        "tank_year": 2007,
        "total_capacity": 12000,
        "compartments": [
            {"capacity": 3000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 4000, "product_code": None},
            {"capacity": 1000, "product_code": None},
        ],
        "status": 'active',
        "notes": 'Propiedad: TL',
    },
    {
        "code": 'L-57',
        "operation": 'TRANSPORTE LIZANDRO',
        "chassis_brand": 'FREIGHTLINER',
        "chassis_year": 2023,
        "tank_brand": None,
        "tank_year": None,
        "total_capacity": 6000,
        "compartments": [
            {"capacity": 1000, "product_code": None},
            {"capacity": 1000, "product_code": None},
            {"capacity": 1000, "product_code": None},
            {"capacity": 1000, "product_code": None},
            {"capacity": 2000, "product_code": None},
        ],
        "status": 'active',
        "notes": 'Propiedad: UP debe pasar a TL',
    },
    {
        "code": 'L-30',
        "operation": 'TRANSPORTE LIZANDRO',
        "chassis_brand": 'INTERNATIONAL',
        "chassis_year": 2018,
        "tank_brand": None,
        "tank_year": None,
        "total_capacity": 6000,
        "compartments": [
            {"capacity": 2000, "product_code": None},
            {"capacity": 1000, "product_code": None},
            {"capacity": 1000, "product_code": None},
            {"capacity": 1000, "product_code": None},
            {"capacity": 1000, "product_code": None},
        ],
        "status": 'active',
        "notes": 'Propiedad: TL debe asar a UP',
    },
    {
        "code": 'L-21',
        "operation": 'JET PUNTA CANA',
        "chassis_brand": 'SCANIA',
        "chassis_year": 2023,
        "tank_brand": 'HEIL',
        "tank_year": 1998,
        "total_capacity": 14500,
        "compartments": [
            {"capacity": 5000, "product_code": 'JET_A1'},
            {"capacity": 9500, "product_code": 'JET_A1'},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-24',
        "operation": 'JET PUNTA CANA',
        "chassis_brand": 'SCANIA SUPER',
        "chassis_year": 2026,
        "tank_brand": 'HEIL',
        "tank_year": 2005,
        "total_capacity": 14500,
        "compartments": [
            {"capacity": 7000, "product_code": 'JET_A1'},
            {"capacity": 7500, "product_code": 'JET_A1'},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-25',
        "operation": 'JET PUNTA CANA',
        "chassis_brand": 'SCANIA SUPER',
        "chassis_year": 2026,
        "tank_brand": 'HEIL',
        "tank_year": 1997,
        "total_capacity": 14500,
        "compartments": [
            {"capacity": 4900, "product_code": 'JET_A1'},
            {"capacity": 9600, "product_code": 'JET_A1'},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-28',
        "operation": 'JET PUNTA CANA',
        "chassis_brand": 'SCANIA SUPER',
        "chassis_year": 2026,
        "tank_brand": 'HEIL',
        "tank_year": 1991,
        "total_capacity": 12900,
        "compartments": [
            {"capacity": 7000, "product_code": 'JET_A1'},
            {"capacity": 5900, "product_code": 'JET_A1'},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-45',
        "operation": 'JET PUNTA CANA',
        "chassis_brand": 'SCANIA SUPER',
        "chassis_year": 2026,
        "tank_brand": 'HEIL',
        "tank_year": 2005,
        "total_capacity": 14000,
        "compartments": [
            {"capacity": 4000, "product_code": 'JET_A1'},
            {"capacity": 3000, "product_code": 'JET_A1'},
            {"capacity": 1000, "product_code": 'JET_A1'},
            {"capacity": 2000, "product_code": 'JET_A1'},
            {"capacity": 4000, "product_code": 'JET_A1'},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-48',
        "operation": 'JET PUNTA CANA',
        "chassis_brand": 'SCANIA SUPER',
        "chassis_year": 2026,
        "tank_brand": 'HEIL',
        "tank_year": 2005,
        "total_capacity": 14000,
        "compartments": [
            {"capacity": 4000, "product_code": 'JET_A1'},
            {"capacity": 3000, "product_code": 'JET_A1'},
            {"capacity": 1000, "product_code": 'JET_A1'},
            {"capacity": 2000, "product_code": 'JET_A1'},
            {"capacity": 4000, "product_code": 'JET_A1'},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-49',
        "operation": 'JET PUNTA CANA',
        "chassis_brand": 'SCANIA SUPER',
        "chassis_year": 2026,
        "tank_brand": 'HEIL',
        "tank_year": 2005,
        "total_capacity": 14000,
        "compartments": [
            {"capacity": 4000, "product_code": 'JET_A1'},
            {"capacity": 3000, "product_code": 'JET_A1'},
            {"capacity": 1000, "product_code": 'JET_A1'},
            {"capacity": 2000, "product_code": 'JET_A1'},
            {"capacity": 4000, "product_code": 'JET_A1'},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-2',
        "operation": 'JET PUNTA CANA',
        "chassis_brand": 'SCANIA',
        "chassis_year": 2021,
        "tank_brand": 'HEIL',
        "tank_year": 2001,
        "total_capacity": 12000,
        "compartments": [
            {"capacity": 4000, "product_code": 'JET_A1'},
            {"capacity": 1500, "product_code": 'JET_A1'},
            {"capacity": 3000, "product_code": 'JET_A1'},
            {"capacity": 3500, "product_code": 'JET_A1'},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-9',
        "operation": 'JET TERPEL',
        "chassis_brand": 'DONFENG',
        "chassis_year": 2024,
        "tank_brand": 'HEIL',
        "tank_year": 2001,
        "total_capacity": 12000,
        "compartments": [
            {"capacity": 4000, "product_code": 'JET_A1'},
            {"capacity": 1500, "product_code": 'JET_A1'},
            {"capacity": 3000, "product_code": 'JET_A1'},
            {"capacity": 3500, "product_code": 'JET_A1'},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-10',
        "operation": 'JET TERPEL',
        "chassis_brand": 'DONFENG',
        "chassis_year": 2024,
        "tank_brand": 'FRUEHAUF',
        "tank_year": 1997,
        "total_capacity": 12000,
        "compartments": [
            {"capacity": 6700, "product_code": 'JET_A1'},
            {"capacity": 5300, "product_code": 'JET_A1'},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-17',
        "operation": 'JET TERPEL',
        "chassis_brand": 'DONFENG',
        "chassis_year": 2024,
        "tank_brand": 'HEIL',
        "tank_year": 1996,
        "total_capacity": 12500,
        "compartments": [
            {"capacity": 3500, "product_code": 'JET_A1'},
            {"capacity": 2100, "product_code": 'JET_A1'},
            {"capacity": 1300, "product_code": 'JET_A1'},
            {"capacity": 2800, "product_code": 'JET_A1'},
            {"capacity": 2800, "product_code": 'JET_A1'},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-18',
        "operation": 'JET TERPEL',
        "chassis_brand": 'DONFENG',
        "chassis_year": 2024,
        "tank_brand": 'HEIL',
        "tank_year": 1996,
        "total_capacity": 12500,
        "compartments": [
            {"capacity": 3500, "product_code": 'JET_A1'},
            {"capacity": 2100, "product_code": 'JET_A1'},
            {"capacity": 1300, "product_code": 'JET_A1'},
            {"capacity": 2800, "product_code": 'JET_A1'},
            {"capacity": 2800, "product_code": 'JET_A1'},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-19',
        "operation": 'JET TERPEL',
        "chassis_brand": 'SCANIA',
        "chassis_year": 2020,
        "tank_brand": 'FRUEHAUF',
        "tank_year": 1990,
        "total_capacity": 12000,
        "compartments": [
            {"capacity": 3400, "product_code": 'JET_A1'},
            {"capacity": 2000, "product_code": 'JET_A1'},
            {"capacity": 1100, "product_code": 'JET_A1'},
            {"capacity": 5500, "product_code": 'JET_A1'},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-34',
        "operation": 'JET TERPEL',
        "chassis_brand": 'SCANIA',
        "chassis_year": 2018,
        "tank_brand": 'HEIL',
        "tank_year": 2001,
        "total_capacity": 12500,
        "compartments": [
            {"capacity": 4000, "product_code": 'JET_A1'},
            {"capacity": 2000, "product_code": 'JET_A1'},
            {"capacity": 2000, "product_code": 'JET_A1'},
            {"capacity": 1500, "product_code": 'JET_A1'},
            {"capacity": 3000, "product_code": 'JET_A1'},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-35',
        "operation": 'JET TERPEL',
        "chassis_brand": 'SCANIA',
        "chassis_year": 2018,
        "tank_brand": 'HEIL',
        "tank_year": 2001,
        "total_capacity": 12500,
        "compartments": [
            {"capacity": 4000, "product_code": 'JET_A1'},
            {"capacity": 2000, "product_code": 'JET_A1'},
            {"capacity": 2000, "product_code": 'JET_A1'},
            {"capacity": 1500, "product_code": 'JET_A1'},
            {"capacity": 3000, "product_code": 'JET_A1'},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'S-1',
        "operation": 'JET TERPEL',
        "chassis_brand": 'DONFENG',
        "chassis_year": 2016,
        "tank_brand": 'HEIL',
        "tank_year": 2007,
        "total_capacity": 12000,
        "compartments": [
            {"capacity": 3000, "product_code": 'JET_A1'},
            {"capacity": 2000, "product_code": 'JET_A1'},
            {"capacity": 2000, "product_code": 'JET_A1'},
            {"capacity": 4000, "product_code": 'JET_A1'},
            {"capacity": 1000, "product_code": 'JET_A1'},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-1',
        "operation": 'UP LIMPIO',
        "chassis_brand": 'SCANIA',
        "chassis_year": 2018,
        "tank_brand": 'HEIL',
        "tank_year": 2003,
        "total_capacity": 12000,
        "compartments": [
            {"capacity": 4000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 1000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 3000, "product_code": None},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-3',
        "operation": 'UP LIMPIO',
        "chassis_brand": 'SCANIA',
        "chassis_year": 2019,
        "tank_brand": 'HEIL',
        "tank_year": 2003,
        "total_capacity": 12000,
        "compartments": [
            {"capacity": 4000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 1000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 3000, "product_code": None},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-13',
        "operation": 'UP LIMPIO',
        "chassis_brand": 'ASHOCK LAYLAND',
        "chassis_year": 2025,
        "tank_brand": 'FRUEHAUF',
        "tank_year": 2018,
        "total_capacity": 10000,
        "compartments": [
            {"capacity": 3000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 1000, "product_code": None},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'A-1',
        "operation": 'UP LIMPIO',
        "chassis_brand": 'FREIGHTLINER',
        "chassis_year": 2013,
        "tank_brand": 'FRUEHAUF',
        "tank_year": 1985,
        "total_capacity": 10000,
        "compartments": [
            {"capacity": 3000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 1000, "product_code": None},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-23',
        "operation": 'UP LIMPIO',
        "chassis_brand": 'FREIGHTLINER',
        "chassis_year": 2012,
        "tank_brand": 'FRUEHAUF',
        "tank_year": 2023,
        "total_capacity": 8000,
        "compartments": [
            {"capacity": 3000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 1000, "product_code": None},
            {"capacity": 1000, "product_code": None},
            {"capacity": 1000, "product_code": None},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-40',
        "operation": 'UP LIMPIO',
        "chassis_brand": 'FREIGHTLINER',
        "chassis_year": 2023,
        "tank_brand": 'RIGIDO',
        "tank_year": None,
        "total_capacity": 6000,
        "compartments": [
            {"capacity": 2000, "product_code": None},
            {"capacity": 1000, "product_code": None},
            {"capacity": 1000, "product_code": None},
            {"capacity": 1000, "product_code": None},
            {"capacity": 1000, "product_code": None},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'F-123',
        "operation": 'UP LIMPIO',
        "chassis_brand": 'STERLING',
        "chassis_year": 2003,
        "tank_brand": 'RIGIDO PROCESO DE PERMISO',
        "tank_year": None,
        "total_capacity": 6000,
        "compartments": [
            {"capacity": 1000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 1000, "product_code": None},
        ],
        "status": 'maintenance',
        "notes": 'Tanque rigido en proceso de permiso',
    },
    {
        "code": 'L-33',
        "operation": 'JUAN DOLIO WOP',
        "chassis_brand": 'SCANIA',
        "chassis_year": 2018,
        "tank_brand": 'HEIL',
        "tank_year": 2000,
        "total_capacity": 12500,
        "compartments": [
            {"capacity": 4000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 1500, "product_code": None},
            {"capacity": 3000, "product_code": None},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-55',
        "operation": 'JUAN DOLIO WOP',
        "chassis_brand": 'SCANIA',
        "chassis_year": 2014,
        "tank_brand": 'HEIL',
        "tank_year": 2025,
        "total_capacity": 10000,
        "compartments": [
            {"capacity": 3000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 1000, "product_code": None},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-56',
        "operation": 'JUAN DOLIO WOP',
        "chassis_brand": 'SCANIA',
        "chassis_year": 2016,
        "tank_brand": 'HEIL',
        "tank_year": 2025,
        "total_capacity": 10000,
        "compartments": [
            {"capacity": 3000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 2000, "product_code": None},
            {"capacity": 1000, "product_code": None},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-20',
        "operation": 'UP LIMPIO RIGIDO',
        "chassis_brand": 'ASHOCK LAYLAND',
        "chassis_year": 2025,
        "tank_brand": None,
        "tank_year": None,
        "total_capacity": 1500,
        "compartments": [
            {"capacity": 1000, "product_code": None},
            {"capacity": 500, "product_code": None},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-26',
        "operation": 'UP LIMPIO RIGIDO',
        "chassis_brand": 'HYUNDAI',
        "chassis_year": 2011,
        "tank_brand": None,
        "tank_year": None,
        "total_capacity": 1500,
        "compartments": [
            {"capacity": 1000, "product_code": None},
            {"capacity": 500, "product_code": None},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'F-1',
        "operation": 'UP LIMPIO RIGIDO',
        "chassis_brand": 'HYUNDAI',
        "chassis_year": 2014,
        "tank_brand": None,
        "tank_year": None,
        "total_capacity": 2500,
        "compartments": [
            {"capacity": 500, "product_code": None},
            {"capacity": 500, "product_code": None},
            {"capacity": 500, "product_code": None},
            {"capacity": 500, "product_code": None},
            {"capacity": 500, "product_code": None},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'F-4',
        "operation": 'UP LIMPIO RIGIDO',
        "chassis_brand": 'INTERNATIONAL',
        "chassis_year": 2017,
        "tank_brand": None,
        "tank_year": None,
        "total_capacity": 3500,
        "compartments": [
            {"capacity": 1500, "product_code": None},
            {"capacity": 700, "product_code": None},
            {"capacity": 1300, "product_code": None},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-51',
        "operation": 'UP LIMPIO RIGIDO',
        "chassis_brand": 'HYUNDAI',
        "chassis_year": 2023,
        "tank_brand": None,
        "tank_year": None,
        "total_capacity": 1500,
        "compartments": [
            {"capacity": 750, "product_code": None},
            {"capacity": 750, "product_code": None},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-52',
        "operation": 'UP LIMPIO RIGIDO',
        "chassis_brand": 'HYUNDAI',
        "chassis_year": 2023,
        "tank_brand": None,
        "tank_year": None,
        "total_capacity": 1500,
        "compartments": [
            {"capacity": 1000, "product_code": None},
            {"capacity": 500, "product_code": None},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-68',
        "operation": 'UP LIMPIO RIGIDO',
        "chassis_brand": 'INTERNATIONAL',
        "chassis_year": 2009,
        "tank_brand": None,
        "tank_year": None,
        "total_capacity": 2800,
        "compartments": [
            {"capacity": 2000, "product_code": None},
            {"capacity": 800, "product_code": None},
        ],
        "status": 'active',
        "notes": 'Propiedad: UP (FRAILIN)',
    },
    {
        "code": 'L-4',
        "operation": 'FUEL OIL',
        "chassis_brand": 'FREIGHTLINER COLUMBIA',
        "chassis_year": 2008,
        "tank_brand": 'HEIL',
        "tank_year": 1987,
        "total_capacity": 10000,
        "compartments": [
            {"capacity": 3000, "product_code": 'FUEL_OIL'},
            {"capacity": 2000, "product_code": 'FUEL_OIL'},
            {"capacity": 2000, "product_code": 'FUEL_OIL'},
            {"capacity": 3000, "product_code": 'FUEL_OIL'},
        ],
        "status": 'out_of_service',
        "notes": 'Accidente Pedernales; en reparacion de motor',
    },
    {
        "code": 'L-6',
        "operation": 'FUEL OIL',
        "chassis_brand": 'FREIGHTLINER',
        "chassis_year": 2013,
        "tank_brand": 'HEIL',
        "tank_year": 1976,
        "total_capacity": 10000,
        "compartments": [
            {"capacity": 6000, "product_code": 'FUEL_OIL'},
            {"capacity": 4000, "product_code": 'FUEL_OIL'},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-7',
        "operation": 'FUEL OIL',
        "chassis_brand": 'FREIGHTLINER',
        "chassis_year": 2011,
        "tank_brand": 'FRUEHAUF',
        "tank_year": 1984,
        "total_capacity": 10000,
        "compartments": [
            {"capacity": 5000, "product_code": 'FUEL_OIL'},
            {"capacity": 2000, "product_code": 'FUEL_OIL'},
            {"capacity": 3000, "product_code": 'FUEL_OIL'},
        ],
        "status": 'maintenance',
        "notes": 'Pendiente renovacion ministerio',
    },
    {
        "code": 'L-11',
        "operation": 'FUEL OIL',
        "chassis_brand": 'FREIGHTLINER',
        "chassis_year": 2011,
        "tank_brand": 'HEIL',
        "tank_year": 1989,
        "total_capacity": 11000,
        "compartments": [
            {"capacity": 3000, "product_code": 'FUEL_OIL'},
            {"capacity": 2000, "product_code": 'FUEL_OIL'},
            {"capacity": 2000, "product_code": 'FUEL_OIL'},
            {"capacity": 1500, "product_code": 'FUEL_OIL'},
            {"capacity": 2500, "product_code": 'FUEL_OIL'},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-15',
        "operation": 'FUEL OIL',
        "chassis_brand": 'FREIGHTLINER',
        "chassis_year": 2012,
        "tank_brand": 'FRUEHAUF',
        "tank_year": 1988,
        "total_capacity": 12000,
        "compartments": [
            {"capacity": 5100, "product_code": 'FUEL_OIL'},
            {"capacity": 6900, "product_code": 'FUEL_OIL'},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-36',
        "operation": 'FUEL OIL',
        "chassis_brand": 'SCANIA',
        "chassis_year": 2018,
        "tank_brand": 'HEIL',
        "tank_year": 2001,
        "total_capacity": 12500,
        "compartments": [
            {"capacity": 4000, "product_code": 'FUEL_OIL'},
            {"capacity": 2000, "product_code": 'FUEL_OIL'},
            {"capacity": 2000, "product_code": 'FUEL_OIL'},
            {"capacity": 1500, "product_code": 'FUEL_OIL'},
            {"capacity": 3000, "product_code": 'FUEL_OIL'},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-44',
        "operation": 'FUEL OIL',
        "chassis_brand": 'FREIGHTLINER COLUMBIA',
        "chassis_year": 2013,
        "tank_brand": 'HEIL',
        "tank_year": 1998,
        "total_capacity": 10000,
        "compartments": [
            {"capacity": 4000, "product_code": 'FUEL_OIL'},
            {"capacity": 3000, "product_code": 'FUEL_OIL'},
            {"capacity": 2000, "product_code": 'FUEL_OIL'},
            {"capacity": 1000, "product_code": 'FUEL_OIL'},
        ],
        "status": 'active',
        "notes": 'Comprado a COSANCA',
    },
    {
        "code": 'L-46',
        "operation": 'FUEL OIL',
        "chassis_brand": 'FREIGHTLINER COLUMBIA',
        "chassis_year": 2013,
        "tank_brand": 'HEIL',
        "tank_year": 1998,
        "total_capacity": 10000,
        "compartments": [
            {"capacity": 4000, "product_code": 'FUEL_OIL'},
            {"capacity": 3000, "product_code": 'FUEL_OIL'},
            {"capacity": 2000, "product_code": 'FUEL_OIL'},
            {"capacity": 1000, "product_code": 'FUEL_OIL'},
        ],
        "status": 'active',
        "notes": 'Comprado a COSANCA',
    },
    {
        "code": 'L-47',
        "operation": 'FUEL OIL',
        "chassis_brand": 'FREIGHTLINER COLUMBIA',
        "chassis_year": 2012,
        "tank_brand": 'HEIL',
        "tank_year": 1999,
        "total_capacity": 10000,
        "compartments": [
            {"capacity": 4000, "product_code": 'FUEL_OIL'},
            {"capacity": 3000, "product_code": 'FUEL_OIL'},
            {"capacity": 2000, "product_code": 'FUEL_OIL'},
            {"capacity": 1000, "product_code": 'FUEL_OIL'},
        ],
        "status": 'active',
        "notes": None,
    },
    {
        "code": 'L-61',
        "operation": 'FUEL OIL',
        "chassis_brand": 'FREIGHTLINER COLUMBIA',
        "chassis_year": 2016,
        "tank_brand": 'HEIL',
        "tank_year": 2012,
        "total_capacity": 10000,
        "compartments": [
            {"capacity": 4000, "product_code": None},
            {"capacity": 1000, "product_code": None},
            {"capacity": 3000, "product_code": None},
            {"capacity": 2000, "product_code": None},
        ],
        "status": 'active',
        "notes": 'Tanque WOP (diesel/gasolina): compartimientos flexibles. Comprado a COSANCA',
    },
]

PRODUCTS = [
    {"code": "FUEL_OIL", "name": "Fuel Oil", "unit": "gal"},
    {"code": "DIESEL_REGULAR", "name": "Diesel Regular", "unit": "gal"},
    {"code": "DIESEL_PREMIUM", "name": "Diesel Premium", "unit": "gal"},
    {"code": "GASOLINA_REGULAR", "name": "Gasolina Regular", "unit": "gal"},
    {"code": "GASOLINA_PREMIUM", "name": "Gasolina Premium", "unit": "gal"},
    {"code": "JET_A1", "name": "Jet A-1", "unit": "gal"},
]

# Coordenadas de la Refineria Dominicana de Petroleos (REFIDOMSA), Haina,
# San Cristobal.
DEPOT = {
    "name": "Refineria Dominicana de Petroleos (REFIDOMSA)",
    "address": "Carretera Sanchez Km. 17.5, Zona Industrial de Haina, San Cristobal",
    "lat": 18.4239,
    "lng": -70.0242,
}
