"""Datos de la flota real de la empresa, anonimizados (sin placas ni VIN).

Fuente: hoja de control de flota de camiones cisterna suministrada por el
cliente. Las fichas originales fueron reemplazadas por codigos genericos
T-01..T-10 y se omitieron placas y numeros de chasis/tanque a peticion
explicita. Capacidades en galones (gal).
"""

FLEET: list[dict] = [
    {
        "code": "T-01",
        "chassis_brand": "FREIGHTLINER COLUMBIA",
        "chassis_year": 2008,
        "tank_brand": "HEIL",
        "tank_year": 1987,
        "product_code": "FUEL_OIL",
        "total_capacity": 10_000,
        "compartments": [3_000, 2_000, 2_000, 3_000],
        "status": "out_of_service",
        "notes": "Accidente Pedernales",
    },
    {
        "code": "T-02",
        "chassis_brand": "FREIGHTLINER",
        "chassis_year": 2013,
        "tank_brand": "HEIL",
        "tank_year": 1976,
        "product_code": "FUEL_OIL",
        "total_capacity": 10_000,
        "compartments": [6_000, 4_000],
        "status": "active",
        "notes": None,
    },
    {
        "code": "T-03",
        "chassis_brand": "FREIGHTLINER",
        "chassis_year": 2011,
        "tank_brand": "FRUEHAUF",
        "tank_year": 1984,
        "product_code": "FUEL_OIL",
        "total_capacity": 10_000,
        "compartments": [5_000, 2_000, 3_000],
        "status": "maintenance",
        "notes": "Pendiente renovacion ministerio",
    },
    {
        "code": "T-04",
        "chassis_brand": "FREIGHTLINER",
        "chassis_year": 2011,
        "tank_brand": "HEIL",
        "tank_year": 1989,
        "product_code": "FUEL_OIL",
        "total_capacity": 11_000,
        "compartments": [3_000, 2_000, 2_000, 1_500, 2_500],
        "status": "active",
        "notes": None,
    },
    {
        "code": "T-05",
        "chassis_brand": "FREIGHTLINER",
        "chassis_year": 2012,
        "tank_brand": "FRUEHAUF",
        "tank_year": 1988,
        "product_code": "FUEL_OIL",
        "total_capacity": 12_000,
        "compartments": [5_100, 6_900],
        "status": "active",
        "notes": None,
    },
    {
        "code": "T-06",
        "chassis_brand": "SCANIA",
        "chassis_year": 2018,
        "tank_brand": "HEIL",
        "tank_year": 2001,
        "product_code": "FUEL_OIL",
        "total_capacity": 12_500,
        "compartments": [4_000, 2_000, 2_000, 1_500, 3_000],
        "status": "active",
        "notes": None,
    },
    {
        "code": "T-07",
        "chassis_brand": "FREIGHTLINER COLUMBIA",
        "chassis_year": 2013,
        "tank_brand": "HEIL",
        "tank_year": 1998,
        "product_code": "FUEL_OIL",
        "total_capacity": 10_000,
        "compartments": [4_000, 3_000, 2_000, 1_000],
        "status": "active",
        "notes": None,
    },
    {
        "code": "T-08",
        "chassis_brand": "FREIGHTLINER COLUMBIA",
        "chassis_year": 2013,
        "tank_brand": "HEIL",
        "tank_year": 1998,
        "product_code": "FUEL_OIL",
        "total_capacity": 10_000,
        "compartments": [4_000, 3_000, 2_000, 1_000],
        "status": "active",
        "notes": None,
    },
    {
        "code": "T-09",
        "chassis_brand": "FREIGHTLINER COLUMBIA",
        "chassis_year": 2012,
        "tank_brand": "HEIL",
        "tank_year": 1999,
        "product_code": "FUEL_OIL",
        "total_capacity": 10_000,
        "compartments": [4_000, 3_000, 2_000, 1_000],
        "status": "active",
        "notes": None,
    },
    {
        "code": "T-10",
        "chassis_brand": "FREIGHTLINER COLUMBIA",
        "chassis_year": 2016,
        "tank_brand": "HEIL",
        "tank_year": 2012,
        "product_code": "WOP",
        "total_capacity": 10_000,
        "compartments": [4_000, 1_000, 3_000, 2_000],
        "status": "active",
        "notes": None,
    },
]

PRODUCTS = [
    {"code": "FUEL_OIL", "name": "Fuel Oil", "unit": "gal"},
    {"code": "WOP", "name": "WOP", "unit": "gal"},
]

# Coordenadas aproximadas de la Refineria Dominicana de Petroleos (REFIDOMSA),
# Haina, San Cristobal. Ajustar con la ubicacion GPS exacta de la planta.
DEPOT = {
    "name": "Refineria Dominicana de Petroleos (REFIDOMSA)",
    "address": "Autopista Las Americas, Haina, San Cristobal, Rep. Dominicana",
    "lat": 18.4173,
    "lng": -70.0339,
}
